---
- name: Configure macOS
  hosts: localhost
  vars:
    mas_installed_apps:
      #: TODO: Install manually from AppStore
      # - name: ClipboardHistory
      #   id: 420939835
      - name: WhatsApp
        id: 1147396723
      - name: Slack
        id: 803453959
      - name: PixelmatorPro
        id: 1289583905
    brew_present_taps:
#      - homebrew/cask
      - homebrew/cask-versions
      - blendle/blendle
      - dtan4/dtan4
      - vladarts/xxxbobrxxx
    brew_absent_taps: []
    brew_present_packages:
      - vault
      - kns
      - git
      - bash-completion
      - python3
      - htop
      - pyenv
      - mc
      - curl
      - ffmpeg
      - watch
      - k8stail
      - wget
      - youtube-dl
      - imagemagick
      - terraform
      - jq
      - yq
      - wakeonlan
      - go
      - kubectl
      - helm
      - awscli
      - go-jsonnet
      - ide-gen
      - goreleaser
    brew_absent_packages: []
    brew_present_casks:
      - google-cloud-sdk
    brew_absent_casks: []
  tasks:
    - include_tasks: tasks/osx-defaults.yaml
      tags: [ osx_defaults ]
    - include_tasks: tasks/applications.yaml
      tags: [ applications ]
    - include_tasks: tasks/mas.yaml
      tags: [ applications, mas ]

    - name: Python system requirements
      tags: [ python ]
      pip:
        executable: pip3
        name:
          - virtualenv
          - virtualenvwrapper
    - name: vp global environment
      tags: [ python ]
      command:
        cmd: virtualenv ~/.virtualenvs/vp --python=/usr/local/bin/python3
        creates: "~/.virtualenvs/vp"
    - name: vp global environment requirements
      tags: [ python ]
      pip:
        executable: ~/.virtualenvs/vp/bin/pip
        name:
          - python-gitlab
          - giturlparse
          - pyyaml

    - name: System configuration directory
      file:
        path: ~/dev/github.com/xxxbobrxxx/system_config
        state: directory
    - name: System configuration clone
      git:
        repo: git@github.com:xxxbobrxxx/system_config.git
        dest: ~/dev/github.com/xxxbobrxxx/system_config
    - name: Global ignore file
      command:
        cmd: git config --global core.excludesfile ~/dev/github.com/xxxbobrxxx/system_config/bashrc/ignore
...
