#: macos

#: TODO: Validate
#- name: Disable auto-correct
#  osx_defaults: key=NSAutomaticSpellingCorrectionEnabled type=bool value=false
#
#- name: Bottom-Left Corner -> Screen Saver
#  osx_defaults: domain=com.apple.dock key={{ item.name }} type=int value={{ item.value }}
#  loop: [{ name: wvous-bl-corner, value: 5 }, { name: wvous-bl-modifier, value: 0 }]
#
#- name: Require password immediately after sleep or screen saver
#  osx_defaults: domain=com.apple.screensaver key={{ item.name }} type=int value={{ item.value }}
#  loop: [{ name: askForPassword, value: 1 }, { name: askForPasswordDelay, value: 5 }]
#
#- name: Resize the Dock
#  osx_defaults: domain=com.apple.dock key=com.apple.dock type=int value=25
#
#- name: Hide the Dock
#  osx_defaults: domain=com.apple.dock key=autohide type=bool value=true

- name: White Chrome
  osx_defaults: domain=com.google.Chrome key=NSRequiresAquaSystemAppearance type=bool value=true

- name: White Chromium
  osx_defaults: domain=org.chromium.Chromium key=NSRequiresAquaSystemAppearance type=bool value=true
